### ISSUE TITLE
Add Linux Support

### ISSUE THREAD

**Issue by PatrickSchiefer** [PatrickSchiefer/AL-Nuget-Helper#2]

**Comment by pkoutsogilas** [comment]
I was able to get it running using mono on Fedora 41. I was using this version of mono: 

```
Mono JIT compiler version 6.12.0.199 (tarball Fri Jul 19 05:23:02 UTC 2024)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

I did a quick and dirty change:

```var result = ChildProcess.execSync(`${paketPath} install `, { cwd: outputDirectory });```

I changed it to:

```var result = ChildProcess.execSync(` mono ${paketPath} install `, { cwd: outputDirectory });```

and configured the folder to: "al-nuget-helper.customPaketExecutablePath": "~/.vscode/extensions/patrickschiefer.al-nuget-helper-0.2.4/tools/windows/paket.exe" to avoid the platform not supported message :)

**Comment by PatrickSchiefer** [comment]
Thank you for the input, I'm waiting for the next release of paket which maybe will use .net 8.0. But until then iw ill habe a look at your solution

**Comment by PatrickSchiefer** [comment]
Linux support via Mono is implemeted now, but maybe will switch to use .net toolset as soon as paket.exe is on .net 8.0
