### ISSUE TITLE
restore command is failed

### ISSUE THREAD

**Issue by vkhutornyi** [PatrickSchiefer/AL-Nuget-Helper#8]
Command failed: \extensions\patrickschiefer.al-nuget-helper-0.2.5\tools\windows\paket.exe install 
Paket failed with
-> Error in paket.dependencies line 9
     PackageName can't contain ':'

Genarated paket.dependencies:
strategy: min
lowest_matching: true
source https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/MSSymbols/nuget/v3/index.json
source https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/AppSourceSymbols/nuget/v3/index.json
nuget Microsoft.Application.symbols >= 25.0.0.0
nuget Microsoft.Platform.symbols >= 1.0.0.0
nuget Microsoft.SystemApplication.symbols.63ca2fa4-4f03-4f2b-a480-172fef340d3f >= 1.0.0.0
nuget Microsoft._Exclude_APIV2_.symbols.10cb69d9-bc8a-4d27-970a-9e110e9db2a5 >= 23.0.0.0
**nuget InsightWorks.DynamicShip:IntegratedShipping.symbols.9c55319d-f3b9-441b-9956-0a0a04decd4b >= 2.0.0.0**

**Comment by PatrickSchiefer** [comment]
Seems like the Normalize function does not remove ":". I will have a look at it.

Does your appname iclude ":"?

**Comment by kine** [comment]
Rule for removing characters is defined as

```
removing chars other than „a-zA-Z0-9_-“, 
```
if you want to be compatible with MS.

**Comment by vkhutornyi** [comment]
> Does your appname iclude ":"?
Yes. The AppName is "Dynamic Ship: Integrated Shipping".
Unfortunately, this is not my app I just need to use it in my customization.

**Comment by PatrickSchiefer** [comment]
There was a problem in the normalization code, it should be solved in 0.2.6
