### ISSUE TITLE
Is Nuget Helper missing dependencies when used in Github Codespace? 

### ISSUE THREAD

**Issue by curateideas** [PatrickSchiefer/AL-Nuget-Helper#9]
Command failed: mono /home/vscode/.vscode-remote/extensions/patrickschiefer.al-nuget-helper-0.2.6/tools/windows/paket.exe install 
/bin/sh: 1: mono: not found

**Comment by PatrickSchiefer** [comment]
Currently the linux support is build up on mono which is not installed on codespaces. It will switch to .net as soon as there is an official version of paket.exe in .net 8.0

Maybe it is possible to install mono in codespaces, but I didn't try this

**Comment by PatrickSchiefer** [comment]
Support for codespaces is now available
